#!/usr/bin/env python3
"""PKG-C1 — Partial static audit: multi-tenancy (company_id) isolation.

SCOPE (read this first):
    This is a *static heuristic* scanner, not a substitute for the full
    18-module manual + live IDOR audit that PKG-C1 in 00_TASK_PACKAGE.md
    asks for. It is the "simple part" of that task: it does NOT run
    against a live server, does NOT create two companies and attempt
    cross-tenant access, and cannot prove absence of an IDOR bug.

    What it DOES do, cheaply and repeatably:
      1. Walk every `presentation/routes/*_router.py` file in every module.
      2. Find endpoints whose path contains an `{..._id}` segment that is
         NOT `company_id` itself (i.e. a resource is looked up by its own
         id — the classic IDOR shape: GET/POST/PATCH/DELETE /thing/{id}).
      3. For the module that endpoint belongs to, check whether the
         corresponding `application/use_cases/*.py` files reference
         `company_id` at all.
      4. Flag any module that has id-based endpoints but whose use-case
         layer never mentions `company_id` as HIGH RISK — that is a
         strong signal the isolation filter is simply missing.
      5. Everything else is marked NEEDS-MANUAL-VERIFICATION: the string
         `company_id` being present proves nothing about whether it's
         actually applied to *this specific* query — only a live IDOR
         test (or careful line-by-line read) can confirm that.

Usage:
    python3 audit_tenancy_isolation.py /path/to/modules > report.md

Exit code is always 0; this is a reporting tool, not a CI gate (see
00_TASK_PACKAGE.md PKG-C1 — findings become separate fix tasks, not
silent fixes here).
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ID_PATH_RE = re.compile(r"\{([a-zA-Z0-9_]*_id)\}")
ROUTE_DECORATOR_RE = re.compile(
    r'@router\.(get|post|put|patch|delete)\(\s*(?:"([^"]*)"|\'([^\']*)\')', re.MULTILINE
)


@dataclass
class ModuleFindings:
    module: str
    id_endpoints: list[str] = field(default_factory=list)
    use_case_files_checked: list[str] = field(default_factory=list)
    company_id_mentions_in_use_cases: int = 0
    router_files: list[str] = field(default_factory=list)


def find_id_endpoints(router_text: str) -> list[str]:
    """Return path strings that contain a non-company_id `{..._id}` segment."""
    endpoints = []
    for method, p1, p2 in ROUTE_DECORATOR_RE.findall(router_text):
        path = p1 or p2
        ids = [seg for seg in ID_PATH_RE.findall(path) if seg != "company_id"]
        if ids:
            endpoints.append(f"{method.upper()} {path or '/'}  (id segments: {ids})")
    return endpoints


def audit(modules_root: Path) -> list[ModuleFindings]:
    results = []
    for module_dir in sorted(p for p in modules_root.iterdir() if p.is_dir()):
        routes_dir = module_dir / "presentation" / "routes"
        use_cases_dir = module_dir / "application" / "use_cases"
        if not routes_dir.exists():
            continue

        mf = ModuleFindings(module=module_dir.name)
        for router_file in sorted(routes_dir.glob("*_router.py")):
            mf.router_files.append(router_file.name)
            text = router_file.read_text(encoding="utf-8", errors="replace")
            eps = find_id_endpoints(text)
            for ep in eps:
                mf.id_endpoints.append(f"{router_file.name}: {ep}")

        if use_cases_dir.exists():
            for uc_file in sorted(use_cases_dir.glob("*.py")):
                if uc_file.name == "__init__.py":
                    continue
                mf.use_case_files_checked.append(uc_file.name)
                text = uc_file.read_text(encoding="utf-8", errors="replace")
                mf.company_id_mentions_in_use_cases += len(re.findall(r"company_id", text))

        results.append(mf)
    return results


def render_report(results: list[ModuleFindings]) -> str:
    lines = []
    lines.append("# PKG-C1 — Static Tenancy-Isolation Scan (partial, heuristic)\n")
    lines.append(
        "Generated by `scripts/audit_tenancy_isolation.py`. This is a **sample/heuristic** "
        "pass, not the full manual+live IDOR audit PKG-C1 asks for. See script docstring "
        "for exact scope and limits.\n"
    )

    high_risk = [m for m in results if m.id_endpoints and m.company_id_mentions_in_use_cases == 0]
    needs_manual = [m for m in results if m.id_endpoints and m.company_id_mentions_in_use_cases > 0]
    no_id_endpoints = [m for m in results if not m.id_endpoints]

    lines.append(f"- Modules scanned: **{len(results)}**")
    lines.append(f"- HIGH RISK (id-based endpoints, zero `company_id` mentions in use cases): **{len(high_risk)}**")
    lines.append(f"- NEEDS-MANUAL-VERIFICATION (id-based endpoints, `company_id` present *somewhere*): **{len(needs_manual)}**")
    lines.append(f"- No id-based endpoints found (nothing to flag here): **{len(no_id_endpoints)}**\n")

    if high_risk:
        lines.append("## HIGH RISK — investigate first\n")
        for m in high_risk:
            lines.append(f"### `{m.module}`")
            lines.append(f"Router files: {', '.join(m.router_files) or '(none)'}")
            lines.append(f"Use-case files checked: {', '.join(m.use_case_files_checked) or '(none found)'}")
            lines.append("Id-based endpoints:")
            for ep in m.id_endpoints:
                lines.append(f"- {ep}")
            lines.append("")

    lines.append("## NEEDS-MANUAL-VERIFICATION — company_id referenced, but not proven applied per-query\n")
    for m in needs_manual:
        lines.append(f"- `{m.module}`: {len(m.id_endpoints)} id-based endpoint(s), "
                      f"{m.company_id_mentions_in_use_cases} `company_id` mention(s) in use cases")

    lines.append("\n## No id-based endpoints detected\n")
    for m in no_id_endpoints:
        lines.append(f"- `{m.module}`")

    lines.append(
        "\n---\n"
        "**Next step per module in NEEDS-MANUAL-VERIFICATION**: run an actual IDOR test "
        "(create resource under company A, request it with company B's token/context, "
        "expect 403/404) for each id-based endpoint listed. Any module in HIGH RISK should "
        "be verified first — it is the most likely place a query forgot to filter by "
        "`company_id` (or filters some queries but not the one the flagged endpoint calls; "
        "this script cannot tell those apart)."
    )
    return "\n".join(lines)


if __name__ == "__main__":
    root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("modules")
    if not root.exists():
        print(f"error: {root} does not exist", file=sys.stderr)
        sys.exit(1)
    print(render_report(audit(root)))
